apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend
spec:
  ports:
    - name: http
      port: 80
      targetPort: 4000
  selector:
    app: backend
  type: LoadBalancer
