apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 7tiuxysa.c1.gra9.container-registry.ovh.net/mydemoproject/frontend:v6
        ports:
        - containerPort: 3000
